Repository chshersh/iris, pull requests merged in 2022-10, with the labels that each got.

#70 Add HLint
  .github/workflows/ci.yml
  .hlint.yaml
  src/Iris/Env.hs
Labels: ⚗️ dx, hacktoberfest-accepted

#71 Fixes #57
  test/Test/Iris/Cli.hs
Labels: cli-options, hacktoberfest-accepted

#72 [#69] Add pre-commit config
  .pre-commit-config.yaml
Labels: ⚗️ dx, hacktoberfest-accepted

#76 [#74] Create Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, ⚗️ dx, hacktoberfest-accepted

#80 fix pre-commit probems (spacing)
  .github/CODEOWNERS
  cabal.project
  iris.cabal
  src/Iris/Cli.hs
  src/Iris/Cli/Interactive.hs
  src/Iris/Cli/Internal.hs
  src/Iris/Cli/ParserInfo.hs
  test/Test/Iris/Cli.hs
Labels: hacktoberfest-accepted

#79 ci: add stan configuration
  .github/workflows/ci.yml
  .gitignore
Labels: CI, ⚗️ dx, hacktoberfest-accepted

#85 [#84] Add support for GHC 9.4.2
  .github/workflows/ci.yml
  cabal.project
  iris.cabal
  stack.yaml
Labels: CI, hacktoberfest-accepted

#83 fixes #58 detect non interactive terminals
  src/Iris/Cli/Interactive.hs
  src/Iris/Env.hs
  test/Test/Iris/Cli.hs
Labels: terminal, hacktoberfest-accepted

#88 [#59] add tests for catching global and local parser conflicts
  test/Test/Iris.hs
  test/Test/Iris/Cli.hs
Labels: test, hacktoberfest-accepted

#87 resolves #16 write usage example using Literate Haskell #16
  examples/playground/Main.hs
  examples/simple-grep/Main.lhs
  examples/simple-grep/README.md
  iris.cabal
Labels: documentation, hacktoberfest-accepted

#92 [#89] Add 'putStdoutColoured' and 'putStderrColoured'
  CHANGELOG.md
  examples/simple-grep/README.md
  src/Iris/Colour/Formatting.hs
Labels: documentation, terminal, hacktoberfest-accepted
