Repository chshersh/iris, pull requests merged in 2022-07, with the labels that each got.

#39 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#40 Add FUNDING.yml
  FUNDING.yml
Labels: documentation

#41 [#17] Write README
  README.md
Labels: documentation

#45 Fix link to CONTRIBUTING.md in README
  README.md
Labels: documentation

#46 [#43] Add MonadUnliftIO instance
  iris.cabal
  src/Iris/App.hs
Labels: enhancement

#48 [#47] Fix CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#49 [#37] Add GHC 9.0.2 support
  .github/workflows/ci.yml
  iris.cabal
Labels: CI

#50 [#38] Add GHC 9.2.3 support
  .github/workflows/ci.yml
  cabal.project
  iris.cabal
Labels: CI

#51 [#42] Support stack
  .github/workflows/ci.yml
  iris.cabal
  stack.yaml
Labels: CI

#54 [#52] Include stack building instructions
  README.md
Labels: documentation
