Repository chshersh/iris, pull requests merged in 2023-03, with the labels that each got.

#111 tutorial: typo
  examples/simple-grep/README.md
Labels: documentation

#118 Replace 'colourista' with 'pretty-terminal'
  examples/simple-grep/README.md
  examples/simple-grep/simple-grep.cabal
  src/Iris/Colour/Formatting.hs
  stack.yaml
Labels: documentation, refactoring

#117 [#9] Implement Yes/No reading functions
  CHANGELOG.md
  iris.cabal
  src/Iris.hs
  src/Iris/Interactive.hs
  src/Iris/Interactive/Question.hs
  test/Test/Iris.hs
  test/Test/Iris/Interactive.hs
  test/Test/Iris/Interactive/Question.hs
Labels: enhancement, test, api:new
