Repository chshersh/iris, pull requests merged in 2023-01, with the labels that each got.

#102 Upgrade CI
  .github/workflows/ci.yml
  iris.cabal
  stack.yaml
Labels: CI

#93 Resolves [#22] Add CLI options to handle colouring
  CHANGELOG.md
  README.md
  iris.cabal
  src/Iris/Cli/Colour.hs
  src/Iris/Cli/Internal.hs
  src/Iris/Cli/ParserInfo.hs
  src/Iris/Cli/TripleOption.hs
  src/Iris/Colour/Detect.hs
  src/Iris/Colour/Mode.hs
  src/Iris/Env.hs
  src/Iris/Settings.hs
  test/Test/Iris/Cli.hs
Labels: cli-options, hacktoberfest-accepted

#95 [#94] Use Text in the simple-grep example to match changed Formatting API
  CHANGELOG.md
  examples/simple-grep/README.md
  iris.cabal
  src/Iris/Colour/Formatting.hs
Labels: hacktoberfest-accepted

#97 Remove the `cmd` parameter from `Tool`, and `cliEnvSettingsRequiredTools` from `CliEnvSettings`
  examples/playground/Main.hs
  examples/simple-grep/README.md
  src/Iris/Env.hs
  src/Iris/Settings.hs
  src/Iris/Tool.hs
  test/Test/Iris/Cli.hs
  test/Test/Iris/Tool.hs
Labels: enhancement, hacktoberfest-accepted, refactoring

#98 Update examples/ folder from stan analysis
  examples/simple-grep/README.md
  iris.cabal
Labels: refactoring
